### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by SeanHood** [sonicsnes/udp-broadcast-relay-redux#1]
Not an issue, but this little utility just sorted out a whole load of issues I was having on my home network. Never had SSDP running reliably between vlans. If you have a donate page or anything I'll send you something.

Also, I have this running on a Ubiquiti Edge Route Lite, (cross-)compiled for the mips64 processor, without any issues.

**Comment by sonicsnes** [comment]
Awesome! Nice to hear it's still working on edgeos. Since I've switched mostly to pfsense myself, that's where most of the changes were tested.
